services:
  - type: web
    name: CodeLadder
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: PYTHON_VERSION
        value: "3.12" render.yaml  it is corredt

